version: '3.8'

services:
  # === FRONTEND ===
  frontend:
    build: ./front_tbank-main
    ports:
      - "80:8081" 
    depends_on:
      - backend
    networks:
      - backend

  # === BACKEND ===
  backend:
    build: ./Tbank-Backend-main
    environment:
      # Настройки PostgreSQL
      - USER=postgres_user
      - PASS=postgres_password
      - DBNAME=tbank
      - DBHOST=postgres
      - DBPORT=5432
      # Настройки JWT
      - APIKEY=your_jwt_secret_here
      # Настройки ML
      - ML_HOST=agents
      - ML_PORT=8766
    depends_on:
      - postgres
      - agents
    networks:
      - agents
      - backend
      - frontend
    # для отладки можно открыть порт:
    ports:
       - "3110:3110"

  agents:
    build:
      context: .
      dockerfile: ./Agents/Dockerfile
    container_name: agents
    restart: unless-stopped
    ports:
      - "8766:8766"
    networks:
      - backend
  # === POSTGRESQL ===
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: tbank  
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
       - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  agents:
    driver: bridge
  frontend:
    driver: bridge



# === VOLUMES ===
volumes:
  pgdata:  # сохраняет данные БД между перезапусками
